import Discovery from '@/components/Dicovery'
import Magic from '@/components/Magic'
import Head from 'next/head'
import Chocolant from '../components/Chocolant';
import Shroom from '@/components/Shroom';
import Voice from '@/components/Voice';
import Contanct from '@/components/Contanct';
import Form from '@/components/Form';
export default function Home() {
  return (
    <>
      <Head>
        <title>updv</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
          <Discovery />
          <Magic />
          <Chocolant />
          <Shroom />
          <Voice />
          <Contanct />
          <Form />
      </main>
    </>
  )
}
